meta:
  Type: Mapped
  ID: SITE
  Description: SITE Data Mapping
  Priority: 3
spec:
  Raw_SITE:
    studyid:
      type: character
      source_col: protocol
    invid:
      type: character
      source_col: pi_number
    InvestigatorFirstName:
      type: character
      source_col: pi_first_name
    InvestigatorLastName:
      type: character
      source_col: pi_last_name
    site_status:
      type: character
    City:
      type: character
      source_col: city
    State:
      type: character
      source_col: state
    Country:
      type: character
      source_col: country
    site_active_dt:
      type: Date
  Mapped_SUBJ:
    studyid:
      type: character
    invid:
      type: character
    subjid:
      type: character
steps:
  - output: Temp_CTMSSiteWide
    name: gsm.core::RunQuery
    params:
      df: Raw_SITE
      strQuery: "SELECT invid as GroupID, * FROM df"
  - output: Temp_CTMSSite
    name: gsm.mapping::MakeLongMeta
    params:
      data: Temp_CTMSSiteWide
      strGroupLevel: 'Site'
  - output: Temp_SiteCountsWide
    name: gsm.core::RunQuery
    params:
      df: Mapped_SUBJ
      strQuery: "SELECT invid as GroupID, COUNT(DISTINCT subjid) as ParticipantCount, COUNT(DISTINCT invid) as SiteCount FROM df GROUP BY invid"
  - output: Temp_SiteCounts
    name: gsm.mapping::MakeLongMeta
    params:
      data: Temp_SiteCountsWide
      strGroupLevel: "Site"
  - output: Mapped_SITE
    name: dplyr::bind_rows
    params:
      Temp_CTMSSite: Temp_CTMSSite
      Temp_SiteCounts: Temp_SiteCounts
