skip_if_not_qualifying()
skip_if_not_installed("rvest")
skip_if_not_installed("shinytest2")

test_that("523: The user can view a card with a high-level overview of the study metadata.", {
  succeed()
  app <- br_app(
    app_dir = "standard",
    name = "523"
  )
  app$wait_for_idle()

  test_that("523.01: The card is the validated card generated by gsm.kri::Report_StudyInfo().", {
    # Header has expected content.
    study_info_card_selector <- "#study_overview-study_information"
    expect_equal(
      app$get_text(paste(study_info_card_selector, ".card-header h5")),
      "Study Information"
    )
    expect_equal(
      app$get_text(paste(
        study_info_card_selector,
        ".card-header .card-subtitle"
      )),
      "Snapshot Date: 2012-03-31"
    )

    # Table is a gsm.kri table.
    expect_css_class(
      app$get_html("body"),
      paste(
        study_info_card_selector,
        "#study_overview-study_information-study_table",
        "table"
      ),
      "gt_table"
    )

    expect_official_screenshot(
      app,
      name = "01-study_info_card",
      selector = study_info_card_selector
    )
  })

  app$stop()
})

test_that("524: The user can view an interactive KRI summary table.", {
  succeed()
  app <- br_app(
    app_dir = "standard",
    name = "524"
  )
  app$wait_for_idle()

  test_that("524.01: The table is the validated group overview generated by `gsm.kri::Widget_GroupOverview()`.", {
    table_selector <- "#study_overview-table"

    expect_css_class(
      app$get_html("body"),
      paste0(table_selector, "-group_overview"),
      c("Widget_GroupOverview", "html-widget")
    )

    expect_official_screenshot(
      app,
      name = "01-kri_summary_table",
      selector = table_selector
    )
  })

  test_that("524.02: The KRI summary table is filtered to the selected 'Group Level'.", {
    table_selector <- "#study_overview-table"

    # Default is "Site"
    expect_equal(app$get_value(input = "group-level-select"), "Site")
    site_labels <- sample_dfGroups %>%
      dplyr::filter(
        .data$GroupLevel == "Site",
        .data$Param == "InvestigatorLastName"
      ) %>%
      dplyr::summarize(
        label = glue::glue("{GroupID} ({Value})"),
        .by = "GroupID"
      ) %>%
      dplyr::pull("label") %>%
      unique()
    expect_in(app$get_text(".group-overview--GroupLabel"), site_labels)
    expect_css_class(
      app$get_html("body"),
      paste0(table_selector, "-group_overview"),
      c("Widget_GroupOverview", "html-widget")
    )
    expect_official_screenshot(
      app,
      name = "02-site"
    )

    # Change to "Country"
    app$set_inputs(`group-level-select` = "Country")
    app$wait_for_idle()
    app$set_inputs(primary_nav_bar = "Study Overview")
    app$wait_for_idle()
    expect_equal(app$get_value(input = "group-level-select"), "Country")
    expect_css_class(
      app$get_html("body"),
      paste0(table_selector, "-group_overview"),
      c("Widget_GroupOverview", "html-widget")
    )
    app$set_inputs(`study_overview-table-kri_counts-red-toggle_pill` = "click")
    app$wait_for_idle()
    country_labels <- sample_dfGroups %>%
      dplyr::filter(.data$GroupLevel == "Country") %>%
      dplyr::pull("GroupID") %>%
      unique() %>%
      sort()
    expect_setequal(
      app$get_text(".group-overview--GroupLabel"),
      country_labels
    )
    expect_official_screenshot(
      app,
      name = "02-country"
    )

    # Reset
    app$set_inputs(`group-level-select` = "Site")
    app$wait_for_idle()
    app$set_inputs(primary_nav_bar = "Study Overview")
    app$wait_for_idle()
    app$set_inputs(`study_overview-table-kri_counts-red-toggle_pill` = "click")
    app$wait_for_idle()
  })

  test_that("524.03: The user can filter the KRI summary table by flag status (red, amber, or both) using clickable pills.", {
    site_results <- gsm.app::sample_dfResults %>%
      dplyr::filter(.data$GroupLevel == "Site") %>%
      gsm.kri::FilterByLatestSnapshotDate()

    # Red (default)
    n_sites_red <- site_results %>%
      dplyr::filter(abs(.data$Flag) == 2) %>%
      dplyr::distinct(.data$GroupID) %>%
      NROW()
    expect_length(app$get_text(".group-overview--GroupLabel"), n_sites_red)
    expect_official_screenshot(
      app,
      name = "03-red_only",
      selector = "#study_overview-table"
    )

    # Amber + red
    n_sites_amber_red <- site_results %>%
      dplyr::filter(abs(.data$Flag) %in% 1:2) %>%
      dplyr::distinct(.data$GroupID) %>%
      NROW()
    app$click(selector = "#study_overview-table-kri_counts-amber-toggle_pill")
    app$wait_for_idle()
    expect_length(
      app$get_text(".group-overview--GroupLabel"),
      n_sites_amber_red
    )
    expect_official_screenshot(
      app,
      name = "03-red_and_amber",
      selector = "#study_overview-table"
    )

    # Amber only
    n_sites_amber <- site_results %>%
      dplyr::filter(abs(.data$Flag) == 1) %>%
      dplyr::distinct(.data$GroupID) %>%
      NROW()
    app$click(selector = "#study_overview-table-kri_counts-red-toggle_pill")
    app$wait_for_idle()
    expect_length(app$get_text(".group-overview--GroupLabel"), n_sites_amber)
    expect_official_screenshot(
      app,
      name = "03-amber_only",
      selector = "#study_overview-table"
    )

    # Click Amber pill to show all
    n_sites_all <- site_results %>%
      dplyr::distinct(.data$GroupID) %>%
      NROW()
    app$click(selector = "#study_overview-table-kri_counts-amber-toggle_pill")
    app$wait_for_idle()
    expect_length(app$get_text(".group-overview--GroupLabel"), n_sites_all)
    expect_official_screenshot(
      app,
      name = "03-all",
      selector = "#study_overview-table"
    )

    # Reset
    app$set_inputs(`study_overview-table-kri_counts-red-toggle_pill` = "click")
    app$wait_for_idle()
  })

  test_that("524.04: The flag status pills display a count of KRIs with that flag status for the selected 'Group Level'.", {
    site_results <- gsm.app::sample_dfResults %>%
      dplyr::filter(.data$GroupLevel == "Site") %>%
      gsm.kri::FilterByLatestSnapshotDate()
    count_site_red <- sum(abs(site_results$Flag) == 2, na.rm = TRUE)
    count_site_amber <- sum(abs(site_results$Flag) == 1, na.rm = TRUE)

    selector_start <- "#study_overview-table-kri_counts"
    expect_equal(
      stringr::str_trim(
        app$get_text(paste0(selector_start, "-red-toggle_pill"))
      ),
      paste(count_site_red, "Red KRIs")
    )
    expect_equal(
      stringr::str_trim(
        app$get_text(paste0(selector_start, "-amber-toggle_pill"))
      ),
      paste(count_site_amber, "Amber KRIs")
    )
    expect_official_screenshot(
      app,
      name = "04-site",
      selector = selector_start
    )

    # Check Country level counts
    app$set_inputs(`group-level-select` = "Country")
    app$wait_for_idle()
    app$set_inputs(primary_nav_bar = "Study Overview")
    app$wait_for_idle()

    country_results <- gsm.app::sample_dfResults %>%
      dplyr::filter(.data$GroupLevel == "Country") %>%
      gsm.kri::FilterByLatestSnapshotDate()
    count_country_red <- sum(abs(country_results$Flag) == 2, na.rm = TRUE)
    count_country_amber <- sum(abs(country_results$Flag) == 1, na.rm = TRUE)
    expect_equal(
      stringr::str_trim(
        app$get_text(paste0(selector_start, "-red-toggle_pill"))
      ),
      paste(count_country_red, "Red KRIs")
    )
    expect_equal(
      stringr::str_trim(
        app$get_text(paste0(selector_start, "-amber-toggle_pill"))
      ),
      paste(count_country_amber, "Amber KRIs")
    )
    expect_official_screenshot(
      app,
      name = "04-country",
      selector = selector_start
    )

    # Reset
    app$set_inputs(`group-level-select` = "Site")
    app$wait_for_idle()
    app$set_inputs(primary_nav_bar = "Study Overview")
    app$wait_for_idle()
  })

  test_that("524.05: Clicking a KRI cell in the summary table navigates the user to the 'Metric Details' tab, filtered to that KRI and group.", {
    # Click a specific cell in the table
    app$click(
      selector = "#study_overview-table tr:nth-child(2) td:nth-child(7)"
    )
    app$wait_for_idle()
    app$run_js(file = test_path("fixtures", "WidgetPlotTestHelpers.js"))
    app$wait_for_js(
      "isCanvasLoaded('metric_details-scatter_plot');",
      timeout = 2000
    )

    # Verify navigation and filtering
    expect_equal(app$get_value(input = "primary_nav_bar"), "Metric Details")
    expect_equal(
      app$get_value(input = "metric_details-metric-select"),
      "Analysis_kri0002"
    )
    targetGroupID <- sample_dfResults %>%
      dplyr::filter(
        .data$GroupLevel == "Site",
        .data$MetricID == "Analysis_kri0002",
        abs(.data$Flag) == 2
      ) %>%
      dplyr::slice(2) %>%
      dplyr::pull("GroupID")
    expect_equal(app$get_value(input = "group-group-select"), targetGroupID)

    expect_official_screenshot(
      app,
      name = "05-table_click_navigation",
      selector = ".navbar"
    )
  })

  app$stop()
})

test_that("525: The user can view a set of interactive scatter plots, one for each KRI.", {
  succeed()
  app <- br_app(
    app_dir = "standard",
    name = "525"
  )
  app$wait_for_idle()
  app$set_inputs(`study_overview-nav_bar` = "Scatter Plots")
  app$wait_for_idle()
  app$run_js(file = test_path("fixtures", "WidgetPlotTestHelpers.js"))
  app$wait_for_js(
    "isCanvasLoaded('study_overview-scatter-Analysis_kri0001');",
    timeout = 5000
  )

  test_that("525.01: The interactive scatter plots are based on `gsm.kri::Widget_ScatterPlot()`.", {
    shared_selector <- "#study_overview-scatter"
    plot_pattern <- paste(
      shared_selector,
      ".bslib-grid-item:not([hidden]) .Widget_ScatterPlot"
    )
    plots <- rvest::read_html(app$get_html("body")) %>%
      rvest::html_elements(plot_pattern)
    n_metrics_site <- sample_dfMetrics %>%
      dplyr::filter(
        .data$GroupLevel == "Site",
        .data$MetricID != "Analysis_srs0001"
      ) %>%
      dplyr::pull("MetricID") %>%
      unique() %>%
      length()
    expect_length(plots, n_metrics_site)
    expect_official_screenshot(
      app,
      name = "01-scatter_plots",
      selector = shared_selector
    )
  })

  test_that("525.02: The set of scatter plots is filtered to show only plots relevant to the selected 'Group Level'.", {
    shared_selector <- "#study_overview-scatter"
    plot_selector <- paste(
      shared_selector,
      ".bslib-grid-item:not([hidden]) .Widget_ScatterPlot"
    )

    # Site
    plots_site <- rvest::read_html(app$get_html("body")) %>%
      rvest::html_elements(plot_selector)
    plot_ids_site <- rvest::html_attr(plots_site, "id")
    n_metrics_site <- sample_dfMetrics %>%
      dplyr::filter(
        .data$GroupLevel == "Site",
        .data$MetricID != "Analysis_srs0001"
      ) %>%
      dplyr::pull("MetricID") %>%
      unique() %>%
      length()
    expect_length(plots_site, n_metrics_site)
    expect_true(all(stringr::str_detect(plot_ids_site, "_kri\\d")))
    expect_official_screenshot(app, name = "02-site")

    # Change to "Country" and check visibility
    app$set_inputs(`group-level-select` = "Country")
    app$wait_for_idle()
    app$set_inputs(primary_nav_bar = "Study Overview")
    app$wait_for_idle()
    app$wait_for_js(
      "isCanvasLoaded('study_overview-scatter-Analysis_cou0001');",
      timeout = 5000
    )

    plots_country <- rvest::read_html(app$get_html("body")) %>%
      rvest::html_elements(plot_selector)
    plot_ids_country <- rvest::html_attr(plots_country, "id")
    n_metrics_country <- sample_dfMetrics %>%
      dplyr::filter(.data$GroupLevel == "Country") %>%
      dplyr::pull("MetricID") %>%
      unique() %>%
      length()
    expect_length(plots_country, n_metrics_country)
    expect_true(all(stringr::str_detect(plot_ids_country, "_cou\\d")))
    expect_official_screenshot(app, name = "02-country")

    # Reset
    app$set_inputs(`group-level-select` = "Site")
    app$wait_for_idle()
    app$set_inputs(primary_nav_bar = "Study Overview")
    app$wait_for_idle()
  })

  test_that("525.03: Clicking a point in a scatter plot navigates the user to the 'Metric Details' tab, filtered to that KRI and group.", {
    targetGroupID <- sample_dfResults %>%
      dplyr::filter(
        .data$GroupLevel == "Site",
        .data$MetricID == "Analysis_kri0002",
        abs(.data$Flag) == 2
      ) %>%
      dplyr::slice(2) %>%
      dplyr::pull("GroupID")

    # Click a point on the second scatter plot
    js <- glue::glue(
      "clickWidgetPlotGroup('study_overview-scatter-Analysis_kri0002', '{targetGroupID}');"
    )
    app$run_js(js)
    app$wait_for_idle()
    app$wait_for_js(
      "isCanvasLoaded('metric_details-scatter_plot');",
      timeout = 2000
    )

    # Verify navigation and filtering
    expect_equal(app$get_value(input = "primary_nav_bar"), "Metric Details")
    expect_equal(
      app$get_value(input = "metric_details-metric-select"),
      "Analysis_kri0002"
    )
    expect_equal(app$get_value(input = "group-group-select"), targetGroupID)

    expect_official_screenshot(
      app,
      name = "03-plot_click_navigation",
      selector = ".navbar"
    )
  })

  app$stop()
})
