skip_if_not_installed("shinytest2")
skip_on_cran <- skip

test_that("BR-SO-01: The user can view a card with a high-level overview of the study metadata, as generated by gsm.kri::Report_StudyInfo().", {
  skip_on_cran()
  app <- AppDriver$new(
    app_dir = test_path("apps", "standard"),
    variant = "br",
    name = "so-01",
    width = 1300,
    height = 800
  )
  app$wait_for_idle()

  # The study overview tab is visible by default.
  # The first column of the layout contains the study information card.
  expect_official_screenshot(
    app,
    name = "study-info-card",
    selector = "div[data-value='Study Overview'] .bslib-col:first-child"
  )

  app$stop()
})

test_that("BR-SO-02: The user can view an interactive KRI summary table based on gsm.kri::Widget_GroupOverview().", {
  skip_on_cran()
  app <- AppDriver$new(
    app_dir = test_path("apps", "standard"),
    variant = "br",
    name = "so-02",
    width = 1300,
    height = 800
  )
  app$wait_for_idle()

  # The KRI summary table is on the "Overview Table" sub-tab by default.
  expect_official_screenshot(
    app,
    name = "kri-summary-table",
    selector = "#study_overview-table"
  )

  app$stop()
})

test_that("BR-SO-03: The KRI summary table is filtered to the selected 'Group Level'.", {
  skip_on_cran()
  app <- AppDriver$new(
    app_dir = test_path("apps", "standard"),
    variant = "br",
    name = "so-03",
    width = 1300,
    height = 800
  )
  app$wait_for_idle()

  # Default is "Site"
  expect_equal(app$get_value(input = "group-level-select"), "Site")
  expect_official_screenshot(
    app,
    name = "site-level-table",
    selector = "#study_overview-table"
  )

  # Change to "Country"
  app$set_inputs(`group-level-select` = "Country")
  app$wait_for_idle()
  expect_equal(app$get_value(input = "group-level-select"), "Country")
  expect_official_screenshot(
    app,
    name = "country-level-table",
    selector = "#study_overview-table"
  )

  app$stop()
})

test_that("BR-SO-04: The user can filter the KRI summary table by flag status (red, amber, or both) using clickable pills.", {
  skip_on_cran()
  app <- AppDriver$new(
    app_dir = test_path("apps", "standard"),
    variant = "br",
    name = "so-04",
    width = 1300,
    height = 800
  )
  app$wait_for_idle()

  fail("BR-SO-04 needs formal tests.")

  app$stop()
})

test_that("BR-SO-05: The flag status pills display a count of KRIs with that flag status for the selected 'Group Level'.", {
  skip_on_cran()
  app <- AppDriver$new(
    app_dir = test_path("apps", "standard"),
    variant = "br",
    name = "so-05",
    width = 1300,
    height = 800
  )
  app$wait_for_idle()

  # Check Site level counts
  site_results <- gsm.app::sample_dfResults %>%
    dplyr::filter(.data$GroupLevel == "Site") %>%
    gsm.kri::FilterByLatestSnapshotDate()
  red_count_site <- sum(abs(site_results$Flag) == 2)
  amber_count_site <- sum(abs(site_results$Flag) == 1)

  expect_equal(app$get_text("#study_overview-table-kri_counts-red-toggle_pill"), paste(red_count_site, "Red KRIs"))
  expect_equal(app$get_text("#study_overview-table-kri_counts-amber-toggle_pill"), paste(amber_count_site, "Amber KRIs"))

  # Check Country level counts
  app$set_inputs(`group-level-select` = "Country")
  app$wait_for_idle()

  country_results <- gsm.app::sample_dfResults %>%
    dplyr::filter(.data$GroupLevel == "Country") %>%
    gsm.kri::FilterByLatestSnapshotDate()
  red_count_country <- sum(abs(country_results$Flag) == 2)
  amber_count_country <- sum(abs(country_results$Flag) == 1)

  expect_equal(app$get_text("#study_overview-table-kri_counts-red-toggle_pill"), paste(red_count_country, "Red KRIs"))
  expect_equal(app$get_text("#study_overview-table-kri_counts-amber-toggle_pill"), paste(amber_count_country, "Amber KRIs"))

  app$stop()
})

test_that("BR-SO-06: Clicking a KRI cell in the summary table navigates the user to the 'Metric Details' tab, filtered to that KRI and group.", {
  skip_on_cran()
  app <- AppDriver$new(
    app_dir = test_path("apps", "standard"),
    variant = "br",
    name = "so-06",
    width = 1300,
    height = 800
  )
  app$wait_for_idle()

  fail("BR-SO-06 needs formal tests.")

  app$stop()
})

test_that("BR-SO-07: The user can view a set of interactive scatter plots based on gsm.kri::Widget_ScatterPlot(), one for each KRI.", {
  skip_on_cran()
  app <- AppDriver$new(
    app_dir = test_path("apps", "standard"),
    variant = "br",
    name = "so-07",
    width = 1300,
    height = 800
  )
  app$wait_for_idle()
  app$set_inputs(`study_overview-nav_bar` = "Scatter Plots")
  app$wait_for_idle()

  app$run_js(file = test_path("fixtures", "WidgetPlotTestHelpers.js"))
  app$wait_for_js(
    "isCanvasLoaded('study_overview-scatter-Analysis_kri0001');",
    timeout = 5000
  )

  expect_official_screenshot(
    app,
    name = "scatter-plots-view",
    selector = "#study_overview-scatter"
  )

  app$stop()
})

test_that("BR-SO-08: The set of scatter plots is filtered to show only plots relevant to the selected 'Group Level'.", {
  skip_on_cran()
  app <- AppDriver$new(
    app_dir = test_path("apps", "standard"),
    variant = "br",
    name = "so-08",
    width = 1300,
    height = 800
  )
  app$wait_for_idle()
  app$set_inputs(`study_overview-nav_bar` = "Scatter Plots")
  app$wait_for_idle()

  # Check visibility for "Site"
  site_plot_selector <- "#study_overview-scatter-Analysis_kri0001"
  country_plot_selector <- "#study_overview-scatter-Analysis_kri0004"
  expect_false(app$get_element(selector = paste0(site_plot_selector, " .chart"))$is_hidden())
  expect_true(app$get_element(selector = paste0(country_plot_selector, " .chart"))$is_hidden())

  # Change to "Country" and check visibility
  app$set_inputs(`group-level-select` = "Country")
  app$wait_for_idle()
  expect_true(app$get_element(selector = paste0(site_plot_selector, " .chart"))$is_hidden())
  expect_false(app$get_element(selector = paste0(country_plot_selector, " .chart"))$is_hidden())

  app$stop()
})

test_that("BR-SO-09: Clicking a point in a scatter plot navigates the user to the 'Metric Details' tab, filtered to that KRI and group.", {
  skip_on_cran()
  app <- AppDriver$new(
    app_dir = test_path("apps", "standard"),
    variant = "br",
    name = "so-09",
    width = 1300,
    height = 800
  )
  app$wait_for_idle()
  app$set_inputs(`study_overview-nav_bar` = "Scatter Plots")
  app$wait_for_idle()

  app$run_js(file = test_path("fixtures", "WidgetPlotTestHelpers.js"))
  app$wait_for_js(
    "isCanvasLoaded('study_overview-scatter-Analysis_kri0001');",
    timeout = 5000
  )

  # Click a point on the first scatter plot
  app$run_js("clickWidgetPlotGroup('study_overview-scatter-Analysis_kri0001', '0X4579');")
  app$wait_for_idle()

  # Verify navigation and filtering
  expect_equal(app$get_value(input = "primary_nav_bar"), "Metric Details")
  expect_equal(app$get_value(input = "metric_details-metric"), "Analysis_kri0001")
  expect_equal(app$get_value(input = "group-group-select"), "0X4579")

  expect_official_screenshot(
    app,
    name = "navigated-to-metric-details",
    selector = "div[data-value='Metric Details']"
  )

  app$stop()
})
