name: Deploy Repo to shinyapps.io
on:
  push:
    branches: [dev, main]
  pull_request:
    branches: [dev, main]
    paths-ignore:
      - 'README.md'
  workflow_dispatch:
    inputs:
      target-deployment:
        description: 'Select the target shinyapps deployment type'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - prod
          - pr

jobs:
  shinyapps-deploy:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Extract repository name
        run: echo "REPO_NAME=${GITHUB_REPOSITORY##*/}" >> $GITHUB_ENV

      - name: Set DEPLOYMENT_TYPE for workflow_dispatch
        if: github.event_name == 'workflow_dispatch'
        run: echo "DEPLOYMENT_TYPE=${{ github.event.inputs.target-deployment }}" >> $GITHUB_ENV

      - name: Set DEPLOYMENT_TYPE for pull requests
        if: github.event_name == 'pull_request'
        run: |
          echo "DEPLOYMENT_TYPE=pr" >> $GITHUB_ENV
          echo "PR_NUMBER=${{ github.event.pull_request.number }}" >> $GITHUB_ENV

      - name: Set DEPLOYMENT_TYPE for pushes to dev
        if: github.event_name == 'push' && github.ref == 'refs/heads/dev'
        run: echo "DEPLOYMENT_TYPE=dev" >> $GITHUB_ENV

      - name: Set DEPLOYMENT_TYPE for pushes to main
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: echo "DEPLOYMENT_TYPE=prod" >> $GITHUB_ENV

      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Install packages
        run: |
          install.packages("pak")
          pak::pak("sessioninfo")

          # Update anything that was installed from cache, etc. rsconnect needs
          # to know how to download the package.
          installed_packages <- sessioninfo::package_info()
          sources <- tolower(installed_packages$source)
          has_other_source <- !(
            startsWith(sources, "cran") |
              startsWith(sources, "github") |
              startsWith(sources, "biocon") |
              grepl("r-universe", sources)
          )
          weird_packages <- installed_packages$package[has_other_source]
          remove.packages(weird_packages)
          pak::pak()
          pak::pak("rsconnect")
          pak::pak(weird_packages)
        shell: Rscript {0}

      - name: Push to shinyapps.io
        env:
          SHINYAPPSIO_TOKEN: ${{ secrets.SHINYAPPSIO_TOKEN }}
          SHINYAPPSIO_SECRET: ${{ secrets.SHINYAPPSIO_SECRET }}
        run: |
          appname <- Sys.getenv("REPO_NAME")
          deployment_type <- Sys.getenv("DEPLOYMENT_TYPE")
          pr_number <- Sys.getenv("PR_NUMBER")

          if (deployment_type != "prod") {
            appname <- paste(appname, deployment_type, sep = "_")
            if (nzchar(pr_number)) {
              appname <- paste(appname, pr_number, sep = "_")
            }
          }
          rsconnect::setAccountInfo(
            name = "openrbqm",
            token = Sys.getenv("SHINYAPPSIO_TOKEN"),
            secret = Sys.getenv("SHINYAPPSIO_SECRET")
          )
          rsconnect::deployApp(
            appName = appname,
            forceUpdate = TRUE
          )
        shell: Rscript {0}
