name: Deploy Repo to shinyapps.io
on:
  push:
    branches: [dev, main]
  pull_request:
    branches: [dev, main]
    paths-ignore:
      - 'README.md'
  workflow_dispatch:
    inputs:
      target-deployment:
        description: 'Select the target shinyapps deployment type'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - prod
          - pr

jobs:
  shinyapps-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Extract repository name
        run: echo "REPO_NAME=${GITHUB_REPOSITORY##*/}" >> $GITHUB_ENV

      - name: Set DEPLOYMENT_TYPE for workflow_dispatch
        if: github.event_name == 'workflow_dispatch'
        run: echo "DEPLOYMENT_TYPE=${{ github.event.inputs.target-deployment }}" >> $GITHUB_ENV

      - name: Set DEPLOYMENT_TYPE for pull requests
        if: github.event_name == 'pull_request'
        run: |
          echo "DEPLOYMENT_TYPE=pr" >> $GITHUB_ENV
          echo "PR_NUMBER=${{ github.event.pull_request.number }}" >> $GITHUB_ENV

      - name: Set DEPLOYMENT_TYPE for pushes to dev
        if: github.event_name == 'push' && github.ref == 'refs/heads/dev'
        run: echo "DEPLOYMENT_TYPE=dev" >> $GITHUB_ENV

      - name: Set DEPLOYMENT_TYPE for pushes to main
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: echo "DEPLOYMENT_TYPE=prod" >> $GITHUB_ENV

      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rsconnect

      - name: Push to shinyapps.io
        env:
          SHINYAPPS_TOKEN: ${{ secrets.SHINYAPPS_TOKEN }}
          SHINYAPPS_SECRET: ${{ secrets.SHINYAPPS_SECRET }}
        run: |
          appname <- Sys.getenv("REPO_NAME")
          deployment_type <- Sys.getenv("DEPLOYMENT_TYPE")
          pr_number <- Sys.getenv("PR_NUMBER")

          if (deployment_type != "prod") {
            appname <- paste(appname, deployment_type, sep = "_")
            if (nzchar(pr_number)) {
              appname <- paste(appname, pr_number, sep = "_")
            }
          }
          rsconnect::setAccountInfo(
            name = "openrbqm"",
            token = Sys.getenv("SHINYAPPS_TOKEN"),
            secret = Sys.getenv("SHINYAPPS_SECRET")
          )
          rsconnect::deployApp(
            appName = appname,
            forceUpdate = TRUE
          )
        shell: Rscript {0}
